### PR TITLE
Automated update from upstream

### PR DESCRIPTION
**Pull request by taylorbot**
This PR was created by the `update-chart` GitHub Actions workflow.
- [x] **:warning: All tests are passing**
- [ ] **:warning: The CHANGELOG.md file has been updated**
- [ ] **:warning: Additional changes in ignored files (see vendir.yml) have been adapted and migrated**

### CODE REVIEW

**Comment by Strigix** [comment]
- Tested this PR on Golem (with altered shared-configs).
- Tested this PR on Golem-stef100 WC (all pods ran fine, rules loaded fine)
- Grafana shows metrics, which aren´t different (such as missing) compared to those of the last week.

**Comment by Strigix** [comment]
Breaking changes:
- Drivers: We have to use modern_ebpf driver now, due to Flatcar having issues. (see https://github.com/falcosecurity/falco/issues/2978)
- K8s collector: We didn't use the -k flag, and our rules, AFAIK, don't use the fields supplied through this.
- Plugins: We don't use any as of now.

**Comment by stone-z** [comment]
We do [use k8s metadata](https://github.com/giantswarm/shared-configs/blob/main/default/apps/falco/configmap-values.yaml.template#L75). I would think this means we need to enable the collector

**Review by stone-z — APPROVED** [review]

**Comment by Strigix** [comment]
Was looking at the wrong places for the -k daemon argument. 
Will follow-up with new PR.

**Pull request merged**
