### PR TITLE
Add CiliumNetworkPolicy for falco-exporter

### PR DESCRIPTION
**Pull request by glitchcrab**
towards https://github.com/giantswarm/giantswarm/issues/29581

### Checklist

- [x] Update changelog in CHANGELOG.md.

**Important:** After this PR is tested and approved, ensure you "Squash and Merge" _unless you are updating a subtree_. The release automation in use on this repository relies on squashing, but git subtrees will be lost if squashed. This repo allows both, so you may need to change the merge type when merging.

### CODE REVIEW

**Comment by glitchcrab** [comment]
this CNP isn't great - i don't like that the selector labels are hard-coded but I cannot use the helpers from the subcharts

**Review by vxav — APPROVED** [review]
Looks sensible

**Review by fhielpos — APPROVED** [review]
LGTM but shouldn't we also allow Prometheus?

**Comment by glitchcrab** [comment]
> LGTM but shouldn't we also allow Prometheus?

that's exactly what this PR is doing - it allows access to the metrics port

**Pull request merged**
