### PR TITLE
Rename falco-app to falco

### PR DESCRIPTION
**Pull request by rewanthtammana**
### Checklist

- [x] Update changelog in CHANGELOG.md.
- [x] Make sure `values.yaml` and `values.schema.json` are valid.
- [x] Test on WC & MC
 
**Important:** After this PR is tested and approved, ensure you "Squash and Merge" _unless you are updating a subtree_. The release automation in use on this repository relies on squashing, but git subtrees will be lost if squashed. This repo allows both, so you may need to change the merge type when merging.

### CODE REVIEW

**Review by fhielpos — COMMENTED** [review]
I don't think we need the schema for the subcharts

**Comment by fhielpos** [comment]
Have you tested this in an MC and WC?

**Comment by rewanthtammana** [comment]
It was failing for `exporter`, [here](https://github.com/giantswarm/falco-app/actions/runs/4013594729/jobs/6893118394)

**Comment by fhielpos** [comment]
Let me see, I believe this should have been fixed. I will trigger some automation

**Review by stone-z — APPROVED** [review]
LGTM!

**Comment by stone-z** [comment]
We might still have to tweak the subchart update automation following this

**Pull request merged**
