### PR TITLE
Update from upstream

### PR DESCRIPTION
**Pull request by architectbot**
This PR has been created from automation in https://github.com/giantswarm/falco-charts

### CODE REVIEW

**Comment by MarcelMue** [comment]
Look at the automation go!

**Comment by MarcelMue** [comment]
cc @ubergesundheit look at this puppy go!

**Comment by ubergesundheit** [comment]
like a boss

**Comment by stone-z** [comment]
It looks like we still have to also bump our chart versions, maybe? https://github.com/giantswarm/falco-app/blob/master/helm/falco-app/Chart.yaml
Should automation do that or is that intentionally a human-in-the-loop thing?

**Comment by MarcelMue** [comment]
> It looks like we still have to also bump our chart versions, maybe? https://github.com/giantswarm/falco-app/blob/master/helm/falco-app/Chart.yaml
> Should automation do that or is that intentionally a human-in-the-loop thing?

Currently it's a human must do it afterwards thing :(

**Review by stone-z — APPROVED** [review]

**Comment by stone-z** [comment]
Why did this only update `falcosidekick` and not also the `falco-exporter` chart?

**Comment by MarcelMue** [comment]
Maybe something is wrong with the automation after all :(

**Pull request merged**
