### PR TITLE
Update from upstream

### PR DESCRIPTION
**Pull request by architectbot**
This PR has been created from automation in https://github.com/giantswarm/falco-charts

### CODE REVIEW

**Comment by stone-z** [comment]
@ubergesundheit I think the automation force replaces changes from earlier charts when it force pushes the later ones. In this line, the [c253cd3](https://github.com/giantswarm/falco-app/commit/c253cd394021dd6741044b50c8db8b92959a959c) commit has falco-exporter changes from upstream but they aren't present in the final PR

>  @architectbot architectbot force-pushed the update-from-upstream branch from 47784e0 to c253cd3 5 minutes ago

**Comment by MarcelMue** [comment]
Yeah I think this is kind of a problem with the setup I tried

Currently we run the automation basically 3 times independently - I thought that would work better. There was a git error before. Maybe I will try to revert.

See here: https://github.com/giantswarm/falco-charts/blob/master/.github/workflows/sync-from-upstream.yaml

**Comment by MarcelMue** [comment]
I fixed this in a pretty _meh_ way:
No more force pushing - pulling -> normal push.

It unfortunately leads to many more commits - but we squash and merge anyway? So not sure.

**Comment by MarcelMue** [comment]
Going with this to make progress.

**Pull request merged**
